footer:
  statistics:
    enable: false
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
  blog_title: "Syferie"
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }
    - {
        key: '工具',
        icon: 'iconfont icon-books',
        submenu: [
          { key: 'Syferie图床', link: 'https://image.chatmagic.pro' },
          { key: 'AI助手', link: 'https://ai.chatmagic.pro' },
          { key: '免费国内NewBing', link: 'http://bing.chatmagic.pro/'}
        ]
      }

index:
  ##进入后的打字机，横条
  slogan:
    enable: true
    text: 欢迎来到Syferie的博客
    api:
      enable: true
      url: "https://zj.v.api.aa1.cn/api/wenan-shici/?type=json"
      method: "GET"
      headers: {}
      keys: ["msg"]


post:
  meta:
    #文章大标题下面的信息
    views:  # 阅读次数
      enable: true
      source: "busuanzi"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"
  comments:
      enable: true
      # 指定的插件，需要同时设置对应插件的必要参数
      # The specified plugin needs to set the necessary parameters at the same time
      # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis | giscus | discuss
      type: twikoo
  # 版权声明，会显示在每篇文章的结尾
  # Copyright, will be displayed at the end of each post
  copyright:
    enable: true
    # CreativeCommons license
    # Options: BY | BY-SA | BY-ND | BY-NC | BY-NC-SA | BY-NC-ND
    license: 'BY'
    # 显示作者
    author:
      enable: true
    # 显示发布日期
    # Show post date
    post_date:
      enable: true
      format: "LL"
    # 显示更新日期
    # Show update date
    update_date:
      enable: false
      format: "LL"
waline:
  serverURL: 'https://myblog-2dw5nwn06-moonwesif.vercel.app'
  path: window.location.pathname
  meta: ['nick', 'mail', 'link']
  requiredMeta: ['nick']
  lang: 'zh-CN'
  emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
  dark: 'html[data-user-color-scheme="dark"]'
  wordLimit: 0
  pageSize: 10
twikoo:
  envId: "https://resonant-sprite-b88983.netlify.app/.netlify/functions/twikoo"
  region: us-east-2
  path: window.location.pathname

about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "Syferie"
  intro: "一个平平无奇的博客，用来随手写点内容"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com", tip: "GitHub" }
    - { class: "iconfont icon-douban-fill", link: "https://douban.com", tip: "豆瓣" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }


